### PR TITLE
Add RedisWrapper support for zcard

### PR DESCRIPTION
**Pull request by bkecskemeti**
Add RedisWrapper support for zcard and scard.

Our team uses Redis sorted sets extensively. We would benefit from sorted set support in zmon.

### CODE REVIEW

**Comment by skokorin** [comment]
:+1:

**Comment by mohabusama** [comment]
@bkecskemeti Thanks! Is it possible to also add ``scard`` to this PR?

**Comment by mohabusama** [comment]
👍

**Comment by lmineiro** [comment]
👍

**Pull request merged**
