### PR TITLE
Adding easy filter for metrics

### PR DESCRIPTION
**Pull request by Jan-M**
Providing basic dict filter to handle common dropwizard use case.

### CODE REVIEW

**Comment by Jan-M** [comment]
:+1:

**Comment by hjacobs** [comment]
Is this thought through? My concerns:

* two functions only differing in name by one character (plural / singular) looks error prone
* function has a semantic name ("metric"), but all it does is filtering some dictionary
* is this good enough or just adding another function helping a specific use case (and we will not be able to get rid of it again easily as soon as people adopt it)

**Comment by Jan-M** [comment]
:+1:

**Comment by mohabusama** [comment]
👍

**Comment by mohabusama** [comment]
@Jan-M Zappr requires specification (some description) in PR body

**Comment by Jan-M** [comment]
:+1:

**Comment by Jan-M** [comment]
:+1:

**Pull request merged**
