### PR TITLE
Improve worker memory consumption

### PR DESCRIPTION
**Pull request by mohabusama**
Load plugin in parent process. Basic testing doesn't seem to show any issues. But needs to be tested more thoroughly.

+ Tested on vagrant, memory was reduced
+ I have noticed memory increase overtime by the worker docker, but can't confirm the reason yet.

### CODE REVIEW

**Comment by hjacobs** [comment]
@mohabusama do you have some benchmarks (nice charts!) to underline your assumption? (paste screenshot here)

**Comment by Jan-M** [comment]
What is the assumption here? shared memory/copy on write semantics?

**Comment by mohabusama** [comment]
I believe COW applies here.

**Comment by mohabusama** [comment]
On vagrant env, mem usage reported by ``docker stats``.

The memory keeps increasing however (not rapidly), but I am suspecting some sort of in-memory caching(may be?). I am still looking into it.

memory usage

**Comment by hjacobs** [comment]
:+1:

**Comment by Jan-M** [comment]
:+1:

**Pull request merged**
