### PR TITLE
add basic auth settings

### PR DESCRIPTION
**Pull request by vetinari**
users can set env var or config to use `http(user="name").code()` to fetch the
password on the fly from plugin.http.basic_auth

### CODE REVIEW

**Comment by vetinari** [comment]
:+1:

**Comment by vetinari** [comment]
addresses #215

**Comment by vetinari** [comment]
:+1:

**Comment by vetinari** [comment]
:+1:

**Comment by Jan-M** [comment]
:-1:

anyone can just use http() with the user to send the password somewhere. Needs to include some url whitelisting similar to our POST method.

**Pull request closed without merging**
