### PR TITLE
Adding Logging and Exception handling for S3 plugin

### PR DESCRIPTION
**Pull request by satybald**
Added exception handling as when zmon-agent doesn't have necessary permission on the bucket, it silently returns -1 for size. Which misleads a user and doesn't provide a correct feedback.

### CODE REVIEW

**Comment by mohabusama** [comment]
Thanks for the PR

I can see some issues that might arise from this approach:
- Errors are masked, which will be harder for building alert conditions (Auth vs Does not exist, etc ...)
- It could break existing functionality (checks/alerts), since it will always raise exceptions (e.g. ``.exists()``won't be useful any more).
- The original concern was to separate behavior on different errors, specifically Auth related errors.

I suggest that we keep the current functionality, while adding ``ClientError`` exception filtering. For instance, in case of Authorization error we raise Exception (may be Connection errors as well?), while other errors we keep current functionality to enable calls to ``.exists`` and ``.size``and apply conditions based on their results in alerts.

What do you think? @satybald

**Comment by satybald** [comment]
yes, make sense. Complete forgot about alerting functionality. To sum up: only Authorization and network connection errors needs to be masked?

**Comment by mohabusama** [comment]
@satybald yes! Let's start with those and see if we need more :)

**Comment by lmineiro** [comment]
Hey @satybald, was wondering if you're still interested in changing the PR to get this merged. Let me know if you do or if we should close the PR. Thanks.

**Comment by satybald** [comment]
I'd love to but at this time I don't have time for that. Feel free to close it.

**Pull request closed without merging**
