### PR TITLE
Add absolute timestamp to Scalyr queries

### PR DESCRIPTION
**Pull request by femueller**
Adding absolute timestamp feature in order to allow more precise Scalyr queries.

### CODE REVIEW

**Comment by femueller** [comment]
👍

**Comment by anton-ryzhov** [comment]
How about to add a timestamp preparation function and use it everywhere in this plugin? That login could become more complex later (like support of `datetime` or so)

Why didn't you add this new values into unittests?

**Comment by femueller** [comment]
> How about to add a timestamp preparation function and use it everywhere in this plugin? That login could become more complex later (like support of datetime or so)

@anton-ryzhov Good idea!

> Why didn't you add this new values into unittests?
Will add too

**Comment by anton-ryzhov** [comment]
:+1:

**Comment by femueller** [comment]
👍

**Comment by pheanex** [comment]
:+1:

**Comment by marcinzaremba** [comment]
👍

**Comment by pitr** [comment]
:+1:

**Pull request merged**
