### PR TITLE
add job-metrics data to check result

### PR DESCRIPTION
**Pull request by vetinari**
this needs to be done here, only here the comnplete entity is available

### CODE REVIEW

**Comment by pitr** [comment]
will adding new fields break data service due to unrecognized fields?

**Comment by vetinari** [comment]
no  - and in doubt, there's https://github.com/zalando-zmon/zmon-data-service/pull/135 also

**Comment by vetinari** [comment]
:+1:

**Comment by pitr** [comment]
ie so DS needs to be deployed first

**Comment by pitr** [comment]
:+1:

**Pull request merged**
