### PR TITLE
Adds support for cloudwatch percentile metrics

### PR DESCRIPTION
**Pull request by gamsd**
Proposed solution to #190.
Feedback wanted (remember that I'm just a Scala dev trying to help in Python land).

### CODE REVIEW

**Comment by rafaelcaricio** [comment]
LGTM. @gamsd please just fix the style errors described in https://travis-ci.org/zalando-zmon/zmon-worker/builds/185209358#L2886-L2887 and it should be good to go.

**Comment by gamsd** [comment]
@rafaelcaricio Done!

**Comment by rafaelcaricio** [comment]
👍

**Comment by mohabusama** [comment]
👍

**Comment by mohabusama** [comment]
@gamsd Thanks for the effort 👍

**Pull request merged**
