### PR TITLE
Add mem_fragmentation_ratio and used_memory_peak

### PR DESCRIPTION
**Pull request by mroderick**
Add `mem_fragmentation_ratio` and `used_memory_peak` to `statistics()`. This will make it easier to detect issues with memory fragmentation in redis instances.

See

* https://redis.io/topics/memory-optimization#memory-allocation
* https://www.datadoghq.com/pdf/Understanding-the-Top-5-Redis-Performance-Metrics.pdf

### CODE REVIEW

**Comment by vetinari** [comment]
:+1:

**Comment by mroderick** [comment]
👍

**Comment by mohabusama** [comment]
Thanks @mroderick. could you please resolve the conflicts?

**Comment by mroderick** [comment]
@mohabusama I've resolved the conflicts

**Comment by mohabusama** [comment]
@mroderick Thanks!

**Comment by mohabusama** [comment]
👍

**Comment by vibhory2j** [comment]
👍

**Comment by vetinari** [comment]
:+1:

**Comment by mroderick** [comment]
Thanks

**Pull request merged**
