### PR TITLE
Provide databaseName as parameter

### PR DESCRIPTION
**Pull request by danielrohe**
This PR provides the possibility to select a database in the sql wrapper
sql(databaseName='mydatabase',shard='shard1').execute('SELECT * FROM blah'). With this you can e.g. have one RDS instance serving multiple databases and in the check define to which database on this RDS instance you want to connect to and execute the statement on.

### CODE REVIEW

**Comment by Jan-M** [comment]
Hmm ... but you can already overwrite the shards={} which allows you to set the connection string incl. the database name?

This would be slightly more convenient though ;)

**Comment by danielrohe** [comment]
Actually that is described nowhere. Can you provide an example?

**Comment by Jan-M** [comment]
Seems we need to show the full overwrite in the docs:

```
  sql(shards={"yourdb":"hostname.domain./yourdb"}).execute()
```

**Comment by danielrohe** [comment]
Its possible with shards, so I think this PR is not needed

**Pull request closed without merging**
