### PR TITLE
Preparing data service sender to include region information

### PR DESCRIPTION
**Pull request by Jan-M**
Some URL stripping as we include the version in config variable.

### CODE REVIEW

**Comment by hjacobs** [comment]
@mohabusama can you review?

**Comment by mohabusama** [comment]
Other than the failing test. 👍

**Comment by hjacobs** [comment]
:-1: because of the failing test (it's related to the change)

**Comment by Jan-M** [comment]
:+1:

**Comment by hjacobs** [comment]
@Jan-M we need to roll out Data Service before this can be merged/used, right?

**Comment by Jan-M** [comment]
Nope this is only to handle config change to only configure base url

**Comment by hjacobs** [comment]
And why do we change that?

**Comment by Jan-M** [comment]
To enable version changes for the different called endpoints.

**Comment by Jan-M** [comment]
the new api for put data is api/v1/data/<account>/<check>/<region>

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
