### PR TITLE
Added dnspython and dns.resolver function

### LINKED ISSUE #119: support CNAME lookups
Please add the support for local execution of the check_dig nagios plugin.

### PR DESCRIPTION
**Pull request by femueller**
This would fix #119 and adds support for CNAME records in zmon.

### CODE REVIEW

**Comment by femueller** [comment]
@mohabusama This would be my proposal. Maybe you're having some thoughts on that.

**Comment by mohabusama** [comment]
@femueller thanks for the PR.

After a small discussion with @hjacobs , the suggestion is to keep ``resolve`` with current implementation (return IP address), and to add another method  ``query`` which takes a ``recordtype`` as done in current implementation.

The only caveat is that the answer is different for different recordtypes, for CNAME ``.target`` is `dns.name.Name`, for TXT it doesn't have a ``.target``. The suggestion is to return list of strings and use ``rdata.to_text()`` or handle each case separately.

Please let me know what you think 😄

**Comment by femueller** [comment]
@mohabusama This sounds pretty good to me too 👍

**Comment by lmineiro** [comment]
@femueller just realized this is still pending. The way I understood it you'd send a few more changes to get this merged. Are you still interested or should we close the PR?

**Comment by femueller** [comment]
@lmineiro I will propose another PR after reviewing it, which will add a query function.

**Comment by lmineiro** [comment]
Closing in preference of #211

**Pull request closed without merging**
