### PR TITLE
add monotonic() helper

### PR DESCRIPTION
**Pull request by vetinari**
usage (returns True / False):
```python
 monotonic(10)
 monotonic(10, strictly=True)
 monotonic(10, increasing=False, strictly=False)
```
...

### CODE REVIEW

**Comment by vetinari** [comment]
would shorten alert 947 to:
```python
def alert():
    capture(length=value)
    if value < 2000:
        return False
    return monotonic(6, increasing=True, strictly=False)
```

**Comment by lmineiro** [comment]
This is great work. I was trying to grasp the meaning of each argument and realized that some docs would've helped. Wanna give it a shot with some docs for this?

**Comment by mohabusama** [comment]
:+1:

**Comment by vetinari** [comment]
:+1:

**Pull request merged**
